#! /bin/bash

# Return a list of available devices for mounting EBS volumes

REGION=$(wget -qO- http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .region)
AZ=$(wget -qO- http://169.254.169.254/latest/meta-data/placement/availability-zone)
ID=$(wget -qO- http://169.254.169.254/latest/meta-data/instance-id)

VOLUMES=$(aws ec2 --region $REGION describe-volumes \
  --filter Name=attachment.instance-id,Values=${ID} \
  | jq -r '.Volumes[] | (.Attachments[]? | .Device + " " + .InstanceId)' \
  | grep $ID \
  | awk '{ print $1 }' \
  | sort)

if [ -e "/dev/xvda" ]; then
  base="/dev/xvd"
elif [ -e "/dev/sda" ]; then
  base="/dev/sd"
elif [ -e "/dev/nvme0" ]; then
  base="/dev/sd"
else
  base="/dev/ebs"
fi

all="fghijklmnop"
for num in $(seq 1 ${#all}); do
  device=${all:$((num-1)):1}
  if ! echo "$VOLUMES" | grep -q "${base}${device}"; then
    echo "${base}${device}"
  fi
done
